import { Language, MenuItem, Translations } from './types';

// For demonstration, a smaller set of fortunes is used.
export const FORTUNES: { [key in Language]: string[] } = {
  [Language.KO]: [
    "오늘은 예상보다 일이 부드럽게 풀릴 거예요.",
    "작은 선택이 의외의 결과를 가져올지도 몰라요.",
    "기다림 속에서 좋은 소식이 들어올 수 있어요.",
    "누군가의 말보다 자신의 감각을 믿어보세요.",
    "머뭇거림이 오히려 좋은 타이밍을 만들어줘요.",
    "오늘의 실수는 내일의 거름이 될 거예요.",
    "감정이 흔들릴수록 중심을 잡는 연습이 필요해요.",
    "예상치 못한 인연이 스쳐 지나갈지도 몰라요.",
    "흐름을 거스르지 말고 따라가 보세요.",
    "조금 늦게 시작해도 괜찮아요.",
    "당신의 말 한마디가 분위기를 바꿀 수 있어요.",
    "새로운 시도가 작은 기쁨을 가져올 거예요.",
    "혼자만의 시간이 필요해요.",
    "생각보다 많은 사람이 당신을 보고 있어요.",
    "대화보다 침묵이 더 진심을 전할 수도 있어요.",
    "평소보다 예리한 감이 작동해요.",
    "우연히 스친 장면이 오래 기억될 거예요.",
    "마음이 가는 대로 움직여도 괜찮은 날이에요.",
    "커피 한 잔의 여유가 하루를 바꿀 수 있어요.",
    "감정보다는 논리가 빛을 발해요.",
    "가까운 사람이 의외의 조언을 해줄지도 몰라요.",
    "무언가를 놓치는 대신 중요한 걸 얻어요.",
    "당신의 균형감이 빛나는 날이에요.",
    "결과보다 과정을 즐기면 좋은 일이 생겨요.",
    "어제의 고민이 오늘은 별일 아닌 게 돼요.",
    "조금의 변화가 큰 활력을 불러옵니다.",
    "상대의 속도를 존중하면 관계가 편안해져요.",
    "의외의 칭찬을 들을지도 몰라요.",
    "단순하게 생각하세요.",
    "한 발 뒤에서 보면 모든 게 다르게 보여요.",
    "무심코 한 행동이 좋은 인상을 남겨요.",
    "작은 행운이 자주 찾아옵니다.",
    "예전의 감정이 다시 찾아올 수 있어요.",
    "기대하지 않았던 순간이 마음을 움직여요.",
    "잠시 멈추면 새로운 길이 보여요.",
    "오늘은 직감이 놀랄 만큼 정확해요.",
    "기분이 방향을 알려주는 나침반이 될 거예요.",
    "당신의 배려가 누군가의 하루를 살려줄지도 몰라요.",
    "평소와 다른 선택이 색다른 결과를 만듭니다.",
    "눈에 보이지 않는 노력이 빛을 발해요.",
    "무리하지 않아도 충분해요.",
    "작은 친절이 큰 변화를 만들 거예요.",
    "바쁘게 움직일수록 중심을 잃지 마세요.",
    "논리보다 공감이 필요해요.",
    "당신의 진심이 전해지는 하루예요.",
    "변화를 두려워하지 마세요.",
    "누군가의 부탁이 새로운 기회를 가져옵니다.",
    "의외의 일이 행운으로 바뀌어요.",
    "감각이 예민해지는 날이에요.",
    "익숙함에서 벗어나면 시야가 넓어져요.",
    "마음이 가벼울수록 일이 잘 풀립니다.",
    "예상치 못한 만남이 있을지도 몰라요.",
    "대화보다 표정이 더 많은 걸 말해요.",
    "당신의 집중력이 빛나는 하루예요.",
    "새로운 루틴이 좋은 기운을 가져와요.",
    "한숨 대신 미소를 택해보세요.",
    "혼란스러워도 괜찮아요.",
    "작지만 꾸준한 노력이 결실을 맺어요.",
    "오늘은 운이 당신 편이에요.",
    "직감이 말하는 방향으로 움직이세요.",
    "마음의 여유를 가져 보세요.",
    "과거를 잊지 말되, 거기에 머물지 마세요.",
    "오늘의 선택이 미래의 기회를 만듭니다.",
    "누군가의 무심한 한마디에 상처받지 마세요.",
    "기분이 가벼워지는 소식을 듣게 될 거예요.",
    "나 자신을 위해 시간을 써보세요.",
    "완벽보다 완성이 더 중요해요.",
    "새로운 기회는 생각보다 가까이 있어요.",
    "조용한 하루를 보낼 거예요.",
    "무심코 지나친 것이 행운의 열쇠일지도 몰라요.",
    "뜻밖의 사람이 당신을 돕습니다.",
    "감정이 안정되면 모든 게 선명해져요.",
    "휴식이 가장 생산적인 선택이에요.",
    "마음이 향하는 곳에 답이 있어요.",
    "당신의 노력이 누군가에게 영감이 돼요.",
    "새로운 시각이 필요해요.",
    "잠시 멈춰 숨을 고르면 길이 보여요.",
    "예상 밖의 타이밍이 좋은 기회를 줍니다.",
    "무리하지 않아도 충분히 괜찮아요.",
    "낯선 일에 호기심을 가져보세요.",
    "불안함 속에서도 성장의 조짐이 보여요.",
    "지나간 일에 너무 많은 의미를 두지 마세요.",
    "평소보다 감정 표현을 많이 할 거예요.",
    "누군가에게 당신의 진심이 닿을 거예요.",
    "과거의 실수가 새로운 통찰이 돼요.",
    "대화에서 배움이 생깁니다.",
    "예상과 달라도 괜찮아요. 그게 인생이에요.",
    "혼자 있는 시간이 힐링이 될 거예요.",
    "마음이 가벼워지는 방향으로 선택하세요.",
    "오늘은 행운이 느리게 찾아옵니다.",
    "예기치 않은 기분 좋은 우연이 생겨요.",
    "오늘의 인내가 내일의 평안을 가져와요.",
    "다정함이 당신의 무기가 될 거예요.",
    "실수는 방향을 알려주는 신호예요.",
    "진심이 통하는 날이에요.",
    "마음의 소리에 귀 기울여보세요.",
    "모든 건 때가 있듯, 오늘은 준비의 날이에요.",
    "당신의 노력이 인정받는 날이에요.",
    "한 걸음 물러서면 새로운 길이 보여요.",
    "다른 사람의 배려를 느낄 수 있는 날이에요.",
    "좋은 생각이 좋은 결과를 부릅니다.",
    "누군가의 무심한 도움에 감동할 거예요.",
    "잊고 있던 감사를 떠올리세요.",
    "여유가 새로운 영감을 줍니다.",
    "단순한 하루가 가장 특별할 수 있어요.",
    "예기치 않은 메시지가 기분을 밝힐 거예요.",
    "잠시 고개를 들면 새로운 풍경이 보여요.",
    "예상치 못한 타이밍에 행운이 찾아올 거예요.",
    "주변의 온기를 느껴보세요.",
    "느리지만 확실히 나아가고 있어요.",
    "결과보다 과정에 집중하세요.",
    "의외의 곳에서 해결책이 나올 거예요.",
    "당신의 진심이 누군가를 웃게 만들어요.",
    "소통이 잘 되는 날이에요.",
    "마음이 가는 곳에 이유가 있어요.",
    "하루의 끝에 작은 위로가 기다립니다.",
    "자신에게 너그러워져야 해요.",
    "의외의 아이디어가 떠오를 거예요.",
    "무심히 흘려보낸 게 다시 돌아옵니다.",
    "스스로를 믿으면 길이 열려요.",
    "평소보다 직관이 명확해요.",
    "당신의 미소가 누군가를 안심시켜요.",
    "행운지수가 서서히 올라가고 있어요.",
    "조급함을 내려놓으면 해결책이 보여요.",
    "낯선 공간에서 영감을 얻어요.",
    "당신의 시도가 누군가에게 영향을 미쳐요.",
    "감사의 표현이 행운을 부릅니다.",
    "반복된 일상 속에서도 새로운 것을 찾아보아요.",
    "작지만 확실한 행복이 다가와요.",
    "혼자보다 함께가 더 좋아요.",
    "무심한 친절이 마음을 녹입니다.",
    "당신의 페이스를 잃지 마세요.",
    "말보다 행동",
    "의외의 제안이 찾아올 수 있어요.",
    "당신의 계획이 구체화되는 날이에요.",
    "좋은 타이밍이 이어집니다.",
    "의외의 감동이 당신을 찾아와요.",
    "숨겨둔 재능이 드러날 거예요.",
    "당신의 꾸준함이 결실을 맺어요.",
    "좋은 기억이 다시 떠오를 거예요.",
    "작은 용기가 큰 변화를 가져옵니다.",
    "균형 잡힌 판단력이 돋보여요.",
    "주변의 신호에 귀 기울여보세요.",
    "평소보다 집중력이 높아요.",
    "말보다 시선이 많은 걸 전해요.",
    "부드러운 태도가 행운을 부릅니다.",
    "감정의 기복이 줄어드는 날이에요.",
    "당신의 선택이 누군가에게 영감을 줘요.",
    "느리게 가도 괜찮아요.",
    "예상치 못한 감사 인사를 듣게 될지도 몰라요.",
    "무리하지 않아도 충분히 괜찮아요.",
    "잊고 있던 꿈을 떠올려보세요.",
    "평온함이 최고의 행운이에요.",
    "당신의 진심이 통하는 날이에요.",
    "기분 좋은 우연이 찾아올 거예요.",
    "마음이 열리면 관계가 풀려요.",
    "익숙한 곳에서 새로움을 발견해요.",
    "작게 웃을 일이 자주 생길 거예요.",
    "예상보다 일이 쉽게 풀립니다.",
    "작은 목표라도 달성의 기쁨을 느껴보세요.",
    "주변 사람에게 기분 좋은 영향을 줘요.",
    "무리한 계획보다 꾸준함을 선택하세요.",
    "당신의 침착함이 빛을 발할 거예요.",
    "작지만 의미 있는 일이 생길 거예요.",
    "주변의 온기가 느껴지는 하루예요.",
    "말보다 행동이 더 큰 힘을 발휘해요.",
    "숨을 고르며 방향을 정하는 날이에요.",
    "평소보다 감정이 깊어지는 하루예요.",
    "당신의 미소가 행운을 끌어당겨요.",
    "타인의 말보다 내면의 소리를 들어보세요.",
    "의외의 사람에게 위로를 받게 됩니다.",
    "꾸준함이 당신의 가장 큰 무기예요.",
    "새로운 가능성이 열립니다.",
    "지나간 일에 마음 쓰지 않아도 괜찮아요.",
    "당신의 긍정적인 태도가 빛을 발합니다.",
    "작지만 기분 좋은 일이 생겨요.",
    "불필요한 걱정을 내려놓으세요.",
    "타인의 시선을 신경 쓰지 않아도 돼요.",
    "바람이 잔잔하면 마음도 차분해져요.",
    "당신의 성실함이 드러나는 하루예요.",
    "잠깐의 우연이 인연으로 이어질지도 몰라요.",
    "‘그냥 괜찮다’는 말이 위로가 됩니다.",
    "기분이 향기로 표현되는 하루예요.",
    "평소보다 솔직해도 괜찮아요.",
    "바쁜 마음을 잠시 내려놓아도 괜찮아요.",
    "당신의 계획이 서서히 현실이 되고 있어요.",
    "스스로를 칭찬하기 좋은 날이에요.",
    "불안함 대신 호기심을 가져보세요.",
    "바람처럼 가벼운 하루가 될 거예요.",
    "당신이 생각보다 강한 사람임을 느낄 거예요.",
    "마음이 풀리는 날이에요.",
    "대화 속에 답이 숨어 있어요.",
    "가벼운 선택이 좋은 결과로 이어집니다.",
    "느슨해지는 게 꼭 나쁜 건 아니에요.",
    "예전보다 한결 단단해진 자신을 보게 될 거예요.",
    "변화를 받아들이기 좋은 날이에요.",
    "자연스러운 흐름을 따르세요.",
    "예상치 못한 칭찬이 당신을 웃게 만듭니다.",
    "지나친 계획보다 즉흥이 좋아요.",
    "새로운 관심사가 생길지도 몰라요.",
    "주변의 도움을 받아도 괜찮아요.",
    "마음이 차분할수록 운이 따릅니다.",
    "당신의 선택이 옳았음을 느끼게 돼요.",
    "주변 사람에게 감사할 일이 생깁니다.",
    "감정의 균형이 잘 잡히는 하루예요.",
    "당신의 집중력이 빛을 발하는 날이에요.",
    "감정의 결이 매끄럽게 이어지는 날이에요.",
    "금전운이 있는 날이에요.",
    "새로운 아이디어가 떠오릅니다.",
    "당신의 노력은 결코 헛되지 않았어요.",
    "당신의 시도가 주목받는 날이에요.",
    "당신의 안정감이 모두에게 전달됩니다.",
    "일상 속에 기분 좋은 일이 숨어 있어요.",
    "감정의 방향이 명확해지는 하루예요.",
    "당신의 존재만으로도 누군가가 안심해요.",
    "무리한 투자는 지양하세요.",
    "흐름을 따라가면 좋은 일이 생겨요.",
    "잊고 있던 자신감을 되찾는 날이에요.",
    "당신의 집중이 성과로 이어져요.",
    "물을 조심하세요.",
    "당신의 침착한 태도가 매력적으로 보입니다.",
    "감사 인사를 전하기 좋은 날이에요.",
    "대화 속에서 영감을 얻습니다.",
    "당신의 평정심이 빛을 발해요.",
    "새로운 아이디어가 현실이 될 수 있어요.",
    "좋은 소식이 들릴지도 몰라요.",
    "오늘은 실수가 오히려 분위기를 풀어요.",
    "당신의 관찰력이 빛나는 날이에요.",
    "당신의 말이 누군가에게 용기가 됩니다.",
    "당신의 따뜻한 시선이 누군가를 살려요.",
    "지나친 고민이 오히려 걸림돌이 될 수 있어요.",
    "기대하지 않은 기쁨이 찾아옵니다.",
    "당신의 노력이 누군가의 본보기가 돼요.",
    "당신의 성실함이 드러납니다.",
    "친구들과의 관계가 돈독해져요.",
    "당신의 진심이 오해를 풀어요.",
    "당신의 말 한마디가 위로가 됩니다.",
    "작은 선택이 큰 차이를 만들어요.",
    "하늘색이 마음의 색과 닮아 있어요.",
    "마음이 말랑해지는 하루예요.",
    "잊고 있던 감정이 따뜻하게 떠오릅니다.",
    "여유로운 산책이 약이 될 거예요.",
    "당신의 진심은 언제나 통합니다.",
    "당신의 집중력이 좋은 결과를 만듭니다.",
    "낯선 길이 오히려 편할 수 있어요.",
    "감정이 차분히 정리되는 하루예요.",
    "늦게 피어난 꽃이 가장 오래갑니다.",
    "당신의 신중함이 빛을 발할 거예요.",
    "당신의 꾸준함이 신뢰로 이어집니다.",
    "지나간 일에 대한 미련이 사라집니다.",
    "평소보다 따뜻한 말이 필요해요.",
    "감정이 부드럽게 녹아드는 하루예요.",
    "생각보다 단순한 해결책이 보입니다.",
    "새로움이 기분 좋은 자극이 됩니다.",
    "생각보다 운은 당신 편이에요.",
    "주변의 작은 소리가 힌트를 줄지도 몰라요.",
    "소소한 기쁨이 여러 번 찾아옵니다.",
    "바람이 마음의 먼지를 털어내 줍니다.",
    "당신의 긍정적인 태도가 길을 엽니다.",
    "조용하지만 의미 있는 하루예요.",
    "지나간 일은 그대로 두어도 괜찮아요.",
    "바쁜 하루에도 여유를 잃지 마세요.",
    "작은 성취가 큰 자신감을 줘요.",
    "조용한 하루 속에도 활력이 있어요.",
    "당신의 부드러운 태도가 매력적으로 보입니다.",
    "대화 속에서 해결책을 찾을 거예요.",
    "평소보다 감정이 깊어져요.",
    "낯선 일에도 자신감이 생겨요.",
    "새로운 일을 시작하는 것보다는 기존에 해 왔던 일에 집중을 해보세요.",
    "몇 차례의 난관이 예상되는 하루입니다.",
    "너무 잘하려 하지 말아요. 이미 충분히 괜찮아요.",
    "계획이 틀어지는 건, 우주의 리허설이에요.",
    "말보다 눈빛이 문제인 날이에요.",
    "오늘은 ‘그럴 수도 있지’가 최고의 주문이에요.",
    "당신의 완벽주의가 잠깐 쉬어야 할 때예요.",
    "핸드폰보다 하늘을 자주 보세요.",
    "생각이 많을수록 행동은 줄어요. 균형을 잡으세요.",
    "주변의 소중한 사람들에게 사랑한다고 말해보세요.",
    "우연히 엎질러진 일이 의외로 좋은 기회를 만듭니다.",
    "무표정이 오해를 부를 수도 있어요.",
    "때로는 기다리는 것이 미덕인 경우가 있습니다.",
    "복잡한 생각은 설탕처럼 천천히 녹여보세요.",
    "너무 조용한 하루에는 작은 실수가 숨어 있어요.",
    "불편함이 나를 바꾸는 첫 신호예요.",
    "작은 차이가 명품을 만듭니다.",
    "급하게 뛰면, 운이 놓칠 수도 있어요.",
    "너무 진지하게 굴면 세상이 장난을 칩니다.",
    "예상치 못한 문제가 발생할 수 있는 날입니다.",
    "기다림이 길면, 운도 크게 온다는 뜻이에요.",
    "감정이 앞서면 판단이 뒤처집니다.",
    "괜히 예감이 맞는 날엔 말수를 줄이세요.",
    "고집은 커피처럼, 진하면 쓰기만 해요.",
    "누군가에게 너무 기대지 마세요.",
    "말 한마디가 분위기를 결정할 수 있어요.",
    "작은 자존심이 큰 오해를 만들 수 있어요.",
    "대화가 꼬이면, 웃음으로 매듭지어보세요.",
    "스스로를 낮추지 말고 본인의 장점을 찾아보세요. 당신은 생각보다 멋진 사람입니다.",
    "타인의 속도를 부러워하지 마세요.",
    "조용한 사람이 제일 많은 걸 알고 있을지도 몰라요.",
    "잘못된 길에서 좋은 풍경을 볼지도 몰라요.",
    "오늘은 한 발 늦게 움직이는 게 정답이에요.",
    "운이 당신을 시험할 수도 있어요.",
    "너무 오래 고민하면 기회가 식어요.",
    "뿌듯하고 보람된 하루가 될 거예요.",
    "겉으로는 멀쩡해 보이지만 기분이 묘한 날이에요.",
    "너무 잘 맞는 사람일수록 거리 조절이 필요해요.",
    "거절을 미루면, 상황이 복잡해져요.",
    "오늘은 빈 잔을 채우지 말고 그대로 두세요.",
    "약간의 빈틈이 매력이 돼요.",
    "너무 큰 계획은 오늘만큼은 내려두세요.",
    "유쾌함 속에 진심을 살짝 숨겨보세요.",
    "‘괜찮다’는 말로 자신을 속이지 마세요.",
    "평소보다 휴식이 더 필요합니다.",
    "칭찬을 받으면 그냥 받아들이세요.",
    "대충 한 일이 의외로 잘 풀릴 수도 있어요.",
    "감정의 과열을 조심하세요.",
    "부드러운 태도가 오히려 강하게 보입니다.",
    "‘괜찮지 않다’고 말해도 괜찮아요.",
    "약간의 무심함이 필요합니다.",
    "감정이 엉뚱한 방향으로 흐를 수 있어요.",
    "어려운 일을 해내면 커다란 보답을 받고 능력을 인정 받는 계기가 될 거예요.",
    "다정함이 지나치면 피로해질 수 있어요.",
    "잔잔한 하루가 가장 안전한 하루예요.",
    "자신을 너무 몰아붙이지 마세요.",
    "오늘은 말보다 타이밍이 중요합니다.",
    "타인의 문제에 너무 깊이 들어가지 마세요.",
    "‘나중에’보다 ‘지금’이 낫습니다.",
    "사소한 일에도 예민할 수 있어요.",
    "너무 빨리 판단하지 마세요.",
    "우연처럼 찾아온 일에 의미를 부여하지 마세요.",
    "감정이 복잡할 땐 손으로 무언가를 만들어보세요.",
    "눈에 보이지 않는 피로가 쌓여 있을 수 있어요.",
    "일보다 사람들과의 관계가 더 어려울 수 있어요.",
    "지나친 배려가 불편함이 될 수도 있어요.",
    "“왜 하필 오늘?”이라는 말이 나올 수도 있어요.",
    "감정이 불안하면 작은 일도 커져 보여요.",
    "불편한 대화일수록 끝까지 들어보세요.",
    "지나친 확신이 오히려 실수가 될 수 있어요.",
    "생각보다 운은 조용히 다가옵니다.",
    "아무 일도 일어나지 않는 것도 하나의 사건이에요.",
    "오늘의 우연이 내일의 이유가 될지도 몰라요.",
    "아무 결론도 내리지 않아도 괜찮아요.",
    "오늘은 한 문장이 마음에 오래 머물 거예요.",
    "운은 친절하지 않지만, 의외로 공정해요.",
    "아무 일도 일어나지 않는 게 다행일 수도 있어요.",
    "누군가를 이해할 힘이 생길지도 몰라요.",
    "새로운 이야기가 시작될지도 몰라요.",
    "예감이 틀리길 바라는 날이에요.",
    "잠시 멈춘다고 해서 멀어진 건 아니에요.",
    "불완전함이 가장 인간적인 순간이에요.",
    "잊으려는 건 대체로 잊히지 않습니다.",
    "사람은 때때로 자신을 속여야 버팁니다.",
    "우연이 의도처럼 보일 수 있어요.",
    "공기가 다정하게 느껴질 수 있어요.",
    "감정이 길을 잃었다가 돌아올 거예요.",
    "커피를 다 마셔도 향이 남는 이유를 생각해보세요.",
    "아무 일 없음을 즐겨보세요.",
    "기억보다 감정이 오래 남을 거예요.",
    "감정이란 결국 하루를 설명하는 또 하나의 언어예요."
  ],
  [Language.EN]: [
    "Things will go more smoothly than you expect today.",
    "A small choice might lead to an unexpected outcome.",
    "Good news might come while you’re waiting.",
    "Trust your instincts more than what others say.",
    "Hesitation might actually lead you to the right timing.",
    "Today’s mistake will help you grow tomorrow.",
    "The more your emotions waver, the more you need to find your balance.",
    "You might cross paths with someone unexpected.",
    "Don’t fight the flow—just go with it.",
    "It’s okay to start a little late.",
    "One word from you could change the whole vibe.",
    "A new try will bring you a small dose of joy.",
    "You need some time to yourself today.",
    "More people are watching you than you think.",
    "Sometimes silence speaks louder than words.",
    "Your intuition is sharper than usual today.",
    "A passing moment might stay with you for a long time.",
    "Go where your heart takes you—it’s that kind of day.",
    "A quiet cup of coffee could change your whole day.",
    "Logic will guide you better than emotion today.",
    "Someone close might surprise you with good advice.",
    "You might lose something small but gain what truly matters.",
    "Your sense of balance shines today.",
    "Focus on the journey, not the result—good things will follow.",
    "Yesterday’s worries won’t seem so big today.",
    "A little change can bring a big burst of energy.",
    "Respecting someone’s pace will make things smoother between you.",
    "You might hear a compliment you didn’t expect.",
    "Keep it simple.",
    "Step back—you’ll see things in a new light.",
    "Something you do without thinking might leave a great impression.",
    "Little bits of luck keep finding you today.",
    "An old feeling might resurface.",
    "An unplanned moment might touch your heart.",
    "Pause for a moment—you’ll see a new path ahead.",
    "Your gut feeling is spot-on today.",
    "Let your mood be your compass today.",
    "Your kindness might just make someone’s day.",
    "A different choice will lead to a fresh result.",
    "Your unseen efforts will finally shine.",
    "You’re doing enough—no need to push too hard.",
    "A small act of kindness will make a big difference.",
    "The busier you get, the more you need to stay centered.",
    "Empathy matters more than logic today.",
    "Your sincerity will reach others today.",
    "Don’t be afraid of change.",
    "A favor for someone might open a new door for you.",
    "Something unexpected will turn out to be lucky.",
    "Your senses are extra sharp today.",
    "Step out of your comfort zone—your view will expand.",
    "The lighter your heart feels, the better things go.",
    "You might run into someone you didn’t expect.",
    "Your expression says more than your words today.",
    "Your focus really shines today.",
    "A new routine will bring fresh energy your way.",
    "Choose a smile over a sigh.",
    "It’s okay to feel a little lost.",
    "Small, steady efforts will finally pay off.",
    "Luck’s on your side today.",
    "Go where your intuition points.",
    "Give yourself a little breathing room.",
    "Remember the past, but don’t stay stuck in it.",
    "The choices you make today will shape tomorrow’s opportunities.",
    "Don’t let someone’s careless words get to you.",
    "You’ll hear some news that lifts your spirits.",
    "Spend some time just for yourself.",
    "Done is better than perfect.",
    "A new opportunity is closer than you think.",
    "A calm, quiet day awaits you.",
    "Something you overlook might be the key to your luck.",
    "Help will come from someone unexpected.",
    "Once your emotions settle, everything becomes clearer.",
    "Rest is the most productive thing you can do today.",
    "The answer lies where your heart points.",
    "Your effort inspires someone today.",
    "You need a fresh perspective.",
    "Take a breath and pause—you’ll see the way forward.",
    "Unexpected timing will bring you a great chance.",
    "You don’t have to push yourself—it’s enough as it is.",
    "Stay curious about something unfamiliar.",
    "Even in your uncertainty, signs of growth are showing.",
    "Don’t overthink what’s already in the past.",
    "You’ll find yourself expressing your feelings more than usual.",
    "Your sincerity will reach someone today.",
    "A past mistake will give you a new insight.",
    "You’ll learn something meaningful from a conversation.",
    "It’s okay if things don’t go as planned—that’s life.",
    "Some alone time will be healing.",
    "Choose the path that makes your heart feel lighter.",
    "Luck comes slowly today—but it’s coming.",
    "A pleasant coincidence will brighten your day.",
    "Today’s patience brings tomorrow’s peace.",
    "Kindness will be your greatest strength.",
    "Mistakes are just signs pointing you the right way.",
    "It’s a day when honesty connects people.",
    "Listen closely to what your heart is saying.",
    "Everything has its time—today is for getting ready.",
    "Your hard work will be recognized today.",
    "Step back a little—you’ll see a new direction.",
    "You’ll feel the kindness of others today.",
    "Good thoughts lead to good outcomes.",
    "Someone’s small act of kindness will move you.",
    "Remember something you’ve been grateful for.",
    "A little breathing space brings new inspiration.",
    "A simple day can turn out to be the most special one.",
    "An unexpected message will brighten your mood.",
    "Look up for a moment—you’ll see a new view.",
    "Luck will show up when you least expect it.",
    "Feel the warmth around you.",
    "You’re moving slowly but surely forward.",
    "Focus on the process, not just the outcome.",
    "The solution might come from an unexpected place.",
    "Your sincerity will bring a smile to someone’s face.",
    "Communication flows easily today.",
    "There’s a reason your heart leads you there.",
    "A small comfort awaits you at the end of the day.",
    "Be gentle with yourself.",
    "An unexpected idea will pop into your mind.",
    "Something you let go of will find its way back to you.",
    "Believe in yourself—the path will open.",
    "Your intuition is clearer than usual today.",
    "Your smile will put someone at ease.",
    "Your luck is slowly rising.",
    "Let go of impatience and the answer will appear.",
    "You’ll find inspiration in an unfamiliar place.",
    "Your efforts are inspiring someone else.",
    "Expressing gratitude brings good fortune.",
    "Look for something new in your daily routine.",
    "Small but certain happiness is on its way.",
    "Together is better than alone today.",
    "A simple act of kindness will warm your heart.",
    "Don’t lose your own pace.",
    "Actions speak louder than words.",
    "You might get an unexpected offer.",
    "Your plans are taking shape today.",
    "Good timing keeps coming your way.",
    "A touching surprise will come to you.",
    "A hidden talent will reveal itself.",
    "Your consistency will finally pay off.",
    "A good memory will come back to you.",
    "A little courage brings big change.",
    "Your sense of balance stands out today.",
    "Pay attention to the signs around you.",
    "Your focus is sharper than usual.",
    "Your eyes say more than your words.",
    "A gentle attitude attracts good luck.",
    "Your emotions will feel more steady today.",
    "Your choices will inspire someone.",
    "It’s okay to take it slow.",
    "You might hear a thank-you you didn’t expect.",
    "You don’t have to push yourself — you’re doing just fine.",
    "Think about a dream you’ve forgotten for a while.",
    "Peace of mind is the best kind of luck.",
    "Today, your sincerity will truly connect with others.",
    "A pleasant coincidence will find you today.",
    "When your heart opens, your relationships follow.",
    "You’ll find something new in a familiar place.",
    "Little reasons to smile will keep showing up.",
    "Things will go more easily than you expect.",
    "Even a small goal can bring big satisfaction.",
    "You’re spreading good vibes to people around you.",
    "Choose consistency over overdoing things.",
    "Your calmness will shine today.",
    "Something small yet meaningful will happen.",
    "You’ll feel warmth all around you today.",
    "Actions will speak louder than words today.",
    "Take a breath — it’s a good day to set your direction.",
    "Your emotions will feel deeper than usual today.",
    "Your smile attracts good luck.",
    "Listen to your inner voice more than others’ words.",
    "Comfort will come from someone unexpected.",
    "Consistency is your strongest weapon.",
    "New possibilities are opening up for you.",
    "You don’t need to dwell on what’s already past.",
    "Your positive attitude will shine bright today.",
    "Something small but delightful will happen.",
    "Let go of the worries you don’t need.",
    "Don’t worry about what others think.",
    "As the wind calms, so does your heart.",
    "Your sincerity and dedication will stand out today.",
    "A brief coincidence might turn into something meaningful.",
    "A simple “It’s okay” can be the best comfort.",
    "Your mood feels like a soft fragrance today.",
    "It’s okay to be more honest than usual.",
    "It’s fine to set aside your busy thoughts for a while.",
    "Your plans are slowly becoming reality.",
    "It’s a perfect day to give yourself some credit.",
    "Replace your anxiety with curiosity.",
    "Today will feel light and breezy.",
    "You’ll realize you’re stronger than you thought.",
    "It’s a day when your heart finally relaxes.",
    "The answer you’re looking for might appear in a conversation.",
    "A lighthearted choice will lead to a good outcome.",
    "It’s not a bad thing to loosen up a little.",
    "You’ll see how much stronger you’ve become.",
    "It’s a good day to embrace change.",
    "Go with the natural flow.",
    "An unexpected compliment will make you smile.",
    "Spontaneity works better than overplanning today.",
    "You might find a new interest today.",
    "It’s okay to accept help from others.",
    "The calmer your heart, the luckier you get.",
    "You’ll realize your choice was the right one.",
    "You’ll find a reason to be thankful for someone today.",
    "Your emotions will stay beautifully balanced today.",
    "Your focus will shine brightly today.",
    "Your emotions will flow smoothly and gently today.",
    "You might have a bit of financial luck today.",
    "A fresh idea will come to you.",
    "Your efforts were never in vain.",
    "Your attempt will catch someone’s attention today.",
    "Your calm energy puts everyone at ease.",
    "Something delightful is hidden in your everyday routine.",
    "You’ll clearly understand where your feelings are headed.",
    "Just your presence brings comfort to someone.",
    "Avoid risky investments today.",
    "Go with the flow — good things will happen.",
    "You’ll rediscover the confidence you’d forgotten.",
    "Your focus will turn into results.",
    "Be careful around water today.",
    "Your calm attitude makes you very appealing.",
    "It’s a perfect day to say thank you.",
    "You’ll find inspiration through a conversation.",
    "Your composure will shine today.",
    "A new idea could become reality.",
    "You might hear some good news.",
    "A small mistake might lighten the mood today.",
    "Your sharp observation stands out today.",
    "Your words will give someone courage.",
    "Your warm gaze could brighten someone’s life.",
    "Overthinking might hold you back today.",
    "Unexpected joy will find you.",
    "Your effort becomes someone’s inspiration.",
    "Your diligence will show today.",
    "Your bond with friends will grow stronger.",
    "Your sincerity will clear up a misunderstanding.",
    "A few kind words from you will comfort someone.",
    "A small choice can make a big difference.",
    "The sky’s color feels just like your mood today.",
    "It’s a day when your heart feels soft and light.",
    "A forgotten feeling will resurface warmly.",
    "A slow walk will do you good.",
    "Your sincerity always gets through.",
    "Your focus will bring great results.",
    "An unfamiliar path might feel surprisingly comfortable.",
    "Your feelings will settle into calm clarity.",
    "The flower that blooms late lasts the longest.",
    "Your thoughtfulness will shine today.",
    "Your consistency builds trust.",
    "You’ll finally let go of lingering regrets.",
    "Warm words mean more than usual today.",
    "Your emotions will melt into calmness today.",
    "The answer might be simpler than you think.",
    "Something new will give you a pleasant spark.",
    "Luck is more on your side than you think.",
    "A quiet sound around you might hold a clue.",
    "Small moments of joy will visit you more than once.",
    "The breeze will clear away the dust in your heart.",
    "Your positive attitude will open new paths.",
    "A quiet yet meaningful day is waiting for you.",
    "It’s okay to leave the past as it is.",
    "Don’t lose your sense of calm, even on a busy day.",
    "A small achievement will give you big confidence.",
    "There’s quiet energy even in a calm day.",
    "Your gentle attitude makes you even more charming.",
    "You’ll find the answer through a conversation.",
    "Your feelings will run deeper than usual today.",
    "You’ll feel confident even in unfamiliar situations.",
    "Instead of starting something new, focus on what you’ve already been doing.",
    "A few obstacles might come your way today.",
    "Don’t try so hard — you’re already doing just fine.",
    "When plans fall apart, it’s just the universe rehearsing.",
    "Today, it’s not your words but your gaze that speaks louder.",
    "Today, the best mantra is “It happens.”",
    "It’s time for your perfectionism to take a short break.",
    "Look up at the sky more often than your phone.",
    "The more you think, the less you move — find your balance.",
    "Tell the people you care about that you love them.",
    "A little accident might turn into a lucky chance.",
    "A blank expression could cause misunderstanding.",
    "Sometimes patience is the greatest virtue.",
    "Let your tangled thoughts dissolve slowly, like sugar.",
    "A quiet day might hide a tiny mistake.",
    "Discomfort is the first sign of change.",
    "It’s the little details that make something special.",
    "If you rush, you might run past your luck.",
    "When you take things too seriously, the world plays tricks on you.",
    "An unexpected issue might pop up today.",
    "The longer the wait, the greater the luck that follows.",
    "When emotions lead, judgment lags behind.",
    "If your gut feeling is too accurate today, talk less.",
    "Stubbornness is like coffee — too strong, and it turns bitter.",
    "Don’t lean too much on someone else.",
    "One word can set the tone for the whole day.",
    "A little pride might cause a big misunderstanding.",
    "If the conversation tangles, end it with a smile.",
    "Don’t underestimate yourself — find your strengths. You’re more amazing than you think.",
    "Don’t envy someone else’s pace.",
    "The quiet ones often know the most.",
    "You might find a beautiful view on the wrong path.",
    "Moving one step slower is the right move today.",
    "Luck might test you a little today.",
    "Overthinking will cool down a good chance.",
    "You’ll end the day feeling proud and fulfilled.",
    "You look fine on the outside, but something feels off inside.",
    "The closer someone feels, the more space you might need.",
    "Delaying a “no” only makes things messier.",
    "Don’t refill your cup today—just leave it as it is.",
    "A little imperfection is part of your charm.",
    "Set aside big plans just for today.",
    "Hide a bit of sincerity behind your humor today.",
    "Don’t tell yourself you’re fine when you’re not.",
    "You need more rest than usual today.",
    "When someone compliments you, just say thank you.",
    "Something you did casually might turn out surprisingly well.",
    "Watch out for emotional burnout.",
    "A gentle approach will make you look even stronger.",
    "It’s okay to say you’re not okay.",
    "A bit of detachment will do you good.",
    "Your emotions might drift in an unexpected direction.",
    "Overcoming a challenge will bring recognition and reward.",
    "Too much kindness can wear you out.",
    "A calm day is the safest kind of day.",
    "Don’t push yourself too hard.",
    "Timing matters more than words today.",
    "Don’t get too involved in someone else’s problem.",
    "Now is better than later.",
    "You might be extra sensitive about small things.",
    "Don’t judge too quickly.",
    "Don’t overanalyze something that just happened by chance.",
    "When your feelings get tangled, make something with your hands.",
    "You might be carrying invisible fatigue.",
    "People might be tougher to handle than work today.",
    "Being too considerate could make things awkward.",
    "You might find yourself saying, “Why today, of all days?”",
    "When emotions shake, even small things look big.",
    "The more uncomfortable the talk, the more you should listen.",
    "Being too sure of yourself might lead to a mistake.",
    "Luck arrives quietly, without a sound.",
    "Even nothing happening is something happening.",
    "Today’s coincidence might be tomorrow’s reason.",
    "It’s okay not to reach a conclusion.",
    "One sentence will linger in your heart today.",
    "Luck isn’t kind, but it’s surprisingly fair.",
    "Sometimes nothing happening is a blessing.",
    "You might find the strength to understand someone.",
    "A new story might begin today.",
    "It’s a day when you hope your hunch is wrong.",
    "A pause doesn’t mean you’re falling behind.",
    "Imperfection is the most human moment.",
    "The things you try to forget usually don’t fade easily.",
    "Sometimes, we have to fool ourselves just to keep going.",
    "Coincidence can sometimes look like fate.",
    "Even the air might feel gentle today.",
    "Your emotions may wander, but they’ll find their way back.",
    "Think about why the scent of coffee lingers even after it’s gone.",
    "Enjoy the calm of nothing happening.",
    "Feelings last longer than memories.",
    "In the end, emotions are just another way to describe a day."
  ],
};

export const LUCKY_COLORS: { [key in Language]: { name: string, hex: string }[] } = {
  [Language.KO]: [
    { name: '흰색', hex: '#FFFFFF' },
    { name: '검정색', hex: '#000000' },
    { name: '회색', hex: '#808080' },
    { name: '빨간색', hex: '#FF0000' },
    { name: '주황색', hex: '#FFA500' },
    { name: '노란색', hex: '#FFFF00' },
    { name: '초록색', hex: '#008000' },
    { name: '파란색', hex: '#0000FF' },
    { name: '보라색', hex: '#800080' },
    { name: '갈색', hex: '#A52A2A' },
  ],
  [Language.EN]: [
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Gray', hex: '#808080' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Green', hex: '#008000' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Purple', hex: '#800080' },
    { name: 'Brown', hex: '#A52A2A' },
  ],
};

export const LUCKY_NUMBERS: number[] = Array.from({ length: 45 }, (_, i) => i + 1);

export const LUCKY_PLACES: { [key in Language]: string[] } = {
  [Language.KO]: [
    "창가 자리", "조용한 구석 테이블", "야외 테라스", "단골 카페", "벽면 콘센트 옆 자리", 
    "따뜻한 조명 아래", "낮은 창문 옆 자리", "카페 카운터 앞", "주차장", "화장실", 
    "회의실", "사무실 창가", "엘리베이터 안", "탕비실", "복도", "자판기 앞", 
    "프린터 앞", "건물 옥상", "화분 근처", "건물 출입구", "침대", "소파", "부엌", 
    "욕실", "창문가", "책상 앞", "옷장 앞", "현관문", "베란다", "식탁 앞", "공원 벤치", 
    "강가 산책로", "해변가", "공원 산책로", "언덕 위", "나무 그늘 아래", "별이 보이는 곳", 
    "번화가", "논밭", "호숫가", "버스 정류장", "횡단보도 앞", "도서관", "영화관", 
    "서점", "공중화장실 거울 앞", "미용실", "편의점", "엘리베이터 로비", "마트"
  ],
  [Language.EN]: [
    "Window Seat", "Quiet Corner Table", "Outdoor Terrace", "Favorite Café", 
    "Seat by the Wall Outlet", "Under the Warm Lights", "Seat by the Low Window", 
    "In Front of the Café Counter", "Parking Lot", "Restroom", "Meeting Room", 
    "Office Window Seat", "Inside the Elevator", "Break Room", "Hallway", 
    "In Front of the Vending Machine", "By the Printer", "Rooftop", "Near the Plant", 
    "Building Entrance", "Bed", "Sofa", "Kitchen", "Bathroom", "By the Window", 
    "At the Desk", "In Front of the Closet", "Front Door", "Balcony", "At the Dining Table", 
    "Park Bench", "Riverside Trail", "By the Beach", "Park Path", "On the Hill", 
    "Under the Tree Shade", "Somewhere Under the Stars", "Busy Street", "Field", "Lakeside", 
    "Bus Stop", "At the Crosswalk", "Library", "Movie Theater", "Bookstore", 
    "In Front of the Restroom Mirror", "Hair Salon", "Convenience Store", "Elevator Lobby", "Supermarket"
  ],
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    image: 'https://raw.githubusercontent.com/narang2022/coffee-fortune-assets-2025/main/cream-matcha-latte.png',
    name: { [Language.KO]: '크림녹차라떼', [Language.EN]: 'Cream Green Tea Latte' },
    description: { [Language.KO]: '진한 녹차에 부드러운 크림을 더한 달콤쌉쌀한 라떼', [Language.EN]: 'A rich green tea latte topped with smooth cream for a sweet and mildly bitter balance.' },
  },
  {
    id: 2,
    image: 'https://raw.githubusercontent.com/narang2022/coffee-fortune-assets-2025/main/cheonggyul-tea.png',
    name: { [Language.KO]: '청귤차', [Language.EN]: 'Green Tangerine Tea' },
    description: { [Language.KO]: '청귤 특유의 상큼함과 달콤함을 느낄 수 있는 차', [Language.EN]: 'A fragrant tea that captures the refreshing and sweet notes of green tangerine.' },
  },
  {
    id: 3,
    image: 'https://raw.githubusercontent.com/narang2022/coffee-fortune-assets-2025/main/cheonggyul-ade.png',
    name: { [Language.KO]: '청귤에이드', [Language.EN]: 'Green Tangerine Ade' },
    description: { [Language.KO]: '톡 쏘는 탄산에 청귤의 상큼함이 더해진 에이드', [Language.EN]: 'A sparkling drink infused with the tangy freshness of green tangerine.' },
  },
  {
    id: 4,
    image: 'https://raw.githubusercontent.com/narang2022/coffee-fortune-assets-2025/main/chestnut-latte.png',
    name: { [Language.KO]: '밤라떼', [Language.EN]: 'Chestnut Latte' },
    description: { [Language.KO]: '달콤고소한 밤맛과 우유의 부드러움이 어우러진 라떼', [Language.EN]: 'A cozy blend of sweet, nutty chestnut flavor and silky milk.' },
  },
  {
    id: 5,
    image: 'https://raw.githubusercontent.com/narang2022/coffee-fortune-assets-2025/main/chestnut-smoothie.png',
    name: { [Language.KO]: '밤스무디', [Language.EN]: 'Chestnut Smoothie' },
    description: { [Language.KO]: '진한 밤 맛을 시원하게 즐길 수 있는 밤스무디', [Language.EN]: 'A creamy, chilled smoothie with the deep, comforting taste of chestnut.' },
  },
];


export const UI_TEXT: Translations = {
  mainTitle: {
    [Language.KO]: '☕ 오늘의 커피 운세',
    [Language.EN]: '☕ Today’s Coffee Fortune',
  },
  viewFortuneButton: {
    [Language.KO]: '오늘의 운세 보기',
    [Language.EN]: 'See Today’s Fortune',
  },
  loadingMessage: {
    [Language.KO]: '당신을 위한 행운의 커피를 내리는 중...',
    [Language.EN]: 'Brewing your lucky coffee...',
  },
  todaysFortune: {
    [Language.KO]: '오늘의 운세',
    [Language.EN]: 'Today’s Fortune',
  },
  luckyItems: {
    [Language.KO]: '오늘의 행운 아이템',
    [Language.EN]: 'Today’s Lucky Item',
  },
  luckyColor: {
    [Language.KO]: '행운의 색',
    [Language.EN]: 'Lucky Color',
  },
  luckyNumber: {
    [Language.KO]: '행운의 숫자',
    [Language.EN]: 'Lucky Number',
  },
  luckyPlace: {
    [Language.KO]: '행운의 장소',
    [Language.EN]: 'Lucky Spot',
  },
  newMenu: {
    [Language.KO]: '가을&겨울 신메뉴',
    [Language.EN]: 'Fall & Winter Specials',
  },
  feedbackPrompt: {
    [Language.KO]: '오늘의 운세는 어떠셨나요?',
    [Language.EN]: 'How was your fortune today?',
  },
  shareButton: {
    [Language.KO]: '공유하기',
    [Language.EN]: 'Share',
  },
  retryButton: {
    [Language.KO]: '다시 뽑기',
    [Language.EN]: 'Try Again',
  },
  viewCount: {
    [Language.KO]: `오늘 {count}명이 운세를 봤어요 ☕`,
    [Language.EN]: `{count} people checked their fortune today ☕`,
  },
  cafeInfo: {
    [Language.KO]: '📍 카페 더에스오피',
    [Language.EN]: '📍 Café The SOP',
  },
  cafeAddress: {
    [Language.KO]: '서울 중구 세종대로 55 지하1층',
    [Language.EN]: 'B1, 55 Sejong-daero, Jung-gu, Seoul',
  },
  shareTitle: {
    [Language.KO]: '오늘의 커피 운세',
    [Language.EN]: 'Today’s Coffee Fortune',
  },
  shareText: {
    [Language.KO]: '오늘 저의 운세를 확인해보세요!',
    [Language.EN]: 'Check out my coffee fortune for today!',
  },
  feedbackToast: {
    [Language.KO]: '소중한 의견 감사합니다!',
    [Language.EN]: 'Thank you for your feedback!',
  },
  shareToast: {
    [Language.KO]: '링크가 클립보드에 복사되었어요!',
    [Language.EN]: 'The link has been copied to your clipboard!',
  },
};